export const homeBody: string;
export const homeContent: string;
export const statistics: string;
export const purpose: string;
export const purposeItem: string;
export const purposeTitle: string;
export const purposeTitleH1: string;
export const purposeTitleH2: string;
export const purposeTime: string;
